# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'AFNetworking', '~> 2.5.4'
pod 'MBProgressHUD', '~> 0.9.1'

target 'AsiaTravelIOS' do

end

target 'AsiaTravelIOSTests' do

end

target 'AsiaTravelIOSUITests' do

end

